version: 2
jobs:
  python_3:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - restore_cache:
          key: vdeps3-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install codecov
            pip install nose
      - save_cache:
          key: vdeps3-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
      - run:
          command: |
            . venv/bin/activate
            nosetests --with-coverage --cover-package=loudml_py loudml_py/tests
      - run:
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - python_3
