version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2
  sonarcloud: sonarsource/sonarcloud@1.0.1

jobs:
  python_3:
    machine:  # Required to mount volumes in docker-compose file
      image: circleci/classic:latest
    steps:
      - checkout

      - run:
          name: Start containers and run coverage tests
          command: |
            set -x
            sudo chown -R 1000:1000 .
            docker-compose up tox

      - codecov/upload:
          file: coverage.xml
      - sonarcloud/scan

workflows:
  version: 2
  build:
    jobs:
      - python_3:
          context: org-global
